/*
 * Supporter_Api | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing AIFolderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AIFolderApiTests : IDisposable
    {
        private AIFolderApi instance;

        public AIFolderApiTests()
        {
            instance = new AIFolderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AIFolderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AIFolderApi
            //Assert.IsType<AIFolderApi>(instance);
        }

        /// <summary>
        /// Test ApiAIFolderAddPost
        /// </summary>
        [Fact]
        public void ApiAIFolderAddPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AIFolderDto aIFolderDto = null;
            //var response = instance.ApiAIFolderAddPost(aIFolderDto);
            //Assert.IsType<AIFolderDto>(response);
        }

        /// <summary>
        /// Test ApiAIFolderAddRangePost
        /// </summary>
        [Fact]
        public void ApiAIFolderAddRangePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<AIFolderDto> aIFolderDto = null;
            //instance.ApiAIFolderAddRangePost(aIFolderDto);
        }

        /// <summary>
        /// Test ApiAIFolderCountGet
        /// </summary>
        [Fact]
        public void ApiAIFolderCountGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAIFolderCountGet();
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAIFolderDeleteAllByRangeDelete
        /// </summary>
        [Fact]
        public void ApiAIFolderDeleteAllByRangeDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> requestBody = null;
            //var response = instance.ApiAIFolderDeleteAllByRangeDelete(requestBody);
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAIFolderDeleteAllDelete
        /// </summary>
        [Fact]
        public void ApiAIFolderDeleteAllDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? areYouSure = null;
            //var response = instance.ApiAIFolderDeleteAllDelete(areYouSure);
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAIFolderDeleteDelete
        /// </summary>
        [Fact]
        public void ApiAIFolderDeleteDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.ApiAIFolderDeleteDelete(id);
        }

        /// <summary>
        /// Test ApiAIFolderGetAllGet
        /// </summary>
        [Fact]
        public void ApiAIFolderGetAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAIFolderGetAllGet();
            //Assert.IsType<List<AIFolderDto>>(response);
        }

        /// <summary>
        /// Test ApiAIFolderGetGet
        /// </summary>
        [Fact]
        public void ApiAIFolderGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.ApiAIFolderGetGet(id);
            //Assert.IsType<AIFolderDto>(response);
        }

        /// <summary>
        /// Test ApiAIFolderGetLastOrDefaultGet
        /// </summary>
        [Fact]
        public void ApiAIFolderGetLastOrDefaultGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAIFolderGetLastOrDefaultGet();
            //Assert.IsType<AIFolderDto>(response);
        }

        /// <summary>
        /// Test ApiAIFolderGetPaginatedGet
        /// </summary>
        [Fact]
        public void ApiAIFolderGetPaginatedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? search = null;
            //string? searchField = null;
            //int? page = null;
            //int? perPage = null;
            //string? sortBy = null;
            //string? sortOrder = null;
            //string? filterBy = null;
            //string? filter = null;
            //instance.ApiAIFolderGetPaginatedGet(search, searchField, page, perPage, sortBy, sortOrder, filterBy, filter);
        }

        /// <summary>
        /// Test ApiAIFolderGetRangeGet
        /// </summary>
        [Fact]
        public void ApiAIFolderGetRangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid>? ids = null;
            //var response = instance.ApiAIFolderGetRangeGet(ids);
            //Assert.IsType<List<AIFolderDto>>(response);
        }

        /// <summary>
        /// Test ApiAIFolderSavePost
        /// </summary>
        [Fact]
        public void ApiAIFolderSavePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AIFolderDto aIFolderDto = null;
            //var response = instance.ApiAIFolderSavePost(aIFolderDto);
            //Assert.IsType<AIFolderDto>(response);
        }
    }
}
