/*
 * Supporter_Api | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing AITopicApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AITopicApiTests : IDisposable
    {
        private AITopicApi instance;

        public AITopicApiTests()
        {
            instance = new AITopicApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AITopicApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AITopicApi
            //Assert.IsType<AITopicApi>(instance);
        }

        /// <summary>
        /// Test ApiAITopicAddPost
        /// </summary>
        [Fact]
        public void ApiAITopicAddPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AITopicDto aITopicDto = null;
            //var response = instance.ApiAITopicAddPost(aITopicDto);
            //Assert.IsType<AITopicDto>(response);
        }

        /// <summary>
        /// Test ApiAITopicAddRangePost
        /// </summary>
        [Fact]
        public void ApiAITopicAddRangePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<AITopicDto> aITopicDto = null;
            //instance.ApiAITopicAddRangePost(aITopicDto);
        }

        /// <summary>
        /// Test ApiAITopicCountGet
        /// </summary>
        [Fact]
        public void ApiAITopicCountGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAITopicCountGet();
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAITopicDeleteAllByRangeDelete
        /// </summary>
        [Fact]
        public void ApiAITopicDeleteAllByRangeDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> requestBody = null;
            //var response = instance.ApiAITopicDeleteAllByRangeDelete(requestBody);
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAITopicDeleteAllDelete
        /// </summary>
        [Fact]
        public void ApiAITopicDeleteAllDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? areYouSure = null;
            //var response = instance.ApiAITopicDeleteAllDelete(areYouSure);
            //Assert.IsType<int>(response);
        }

        /// <summary>
        /// Test ApiAITopicDeleteDelete
        /// </summary>
        [Fact]
        public void ApiAITopicDeleteDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.ApiAITopicDeleteDelete(id);
        }

        /// <summary>
        /// Test ApiAITopicGetAllGet
        /// </summary>
        [Fact]
        public void ApiAITopicGetAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAITopicGetAllGet();
            //Assert.IsType<List<AITopicDto>>(response);
        }

        /// <summary>
        /// Test ApiAITopicGetGet
        /// </summary>
        [Fact]
        public void ApiAITopicGetGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.ApiAITopicGetGet(id);
            //Assert.IsType<AITopicDto>(response);
        }

        /// <summary>
        /// Test ApiAITopicGetLastOrDefaultGet
        /// </summary>
        [Fact]
        public void ApiAITopicGetLastOrDefaultGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAITopicGetLastOrDefaultGet();
            //Assert.IsType<AITopicDto>(response);
        }

        /// <summary>
        /// Test ApiAITopicGetPaginatedGet
        /// </summary>
        [Fact]
        public void ApiAITopicGetPaginatedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? search = null;
            //string? searchField = null;
            //int? page = null;
            //int? perPage = null;
            //string? sortBy = null;
            //string? sortOrder = null;
            //string? filterBy = null;
            //string? filter = null;
            //instance.ApiAITopicGetPaginatedGet(search, searchField, page, perPage, sortBy, sortOrder, filterBy, filter);
        }

        /// <summary>
        /// Test ApiAITopicGetRangeGet
        /// </summary>
        [Fact]
        public void ApiAITopicGetRangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid>? ids = null;
            //var response = instance.ApiAITopicGetRangeGet(ids);
            //Assert.IsType<List<AITopicDto>>(response);
        }

        /// <summary>
        /// Test ApiAITopicSavePost
        /// </summary>
        [Fact]
        public void ApiAITopicSavePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AITopicDto aITopicDto = null;
            //var response = instance.ApiAITopicSavePost(aITopicDto);
            //Assert.IsType<AITopicDto>(response);
        }
    }
}
