global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Supporter_Uno.DataContracts;
global using Supporter_Uno.DataContracts.Serialization;
global using Supporter_Uno.Models;
global using Supporter_Uno.Presentation;
global using Supporter_Uno.Services.Caching;
global using Supporter_Uno.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
